In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\samsung1\.venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\samsung1\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\Users\samsung1\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/10.0 MB 8.6 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/10.0 MB 17.2 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 22.2 MB/s  0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.5 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
df = pd.read_csv('data/gapminder.tsv', sep='\t')

In [5]:
df.head()       # ()안에 숫자없으면 기본값 5개만 보여줌

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [11]:
df.head(3)

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710

In [13]:
df.tail()       # ()안에 숫자없으면 기본값 5개만 보여줌
                # 가장 뒤에 있는 5개만 보여줌

       country continent  year  lifeExp       pop   gdpPercap
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [6]:
type(df)

pandas.DataFrame

In [7]:
# shape : 데이터 프레임의 행과 열의 개수(크기 정보)를 튜플로 반환
df.shape    # 행(column)이 1704개, 열(row)이 6개

(1704, 6)

In [8]:
df.columns  # 데이터 프레임의 열 이름 (정보) 확인

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='str')

In [9]:
df.dtypes   # 데이터 프레임의 모든 각 열의 데이터 타입(자료형) 확인

country          str
continent        str
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [10]:
df.info()   # 데이터 프레임의 요약(상세) 정보 확인

<class 'pandas.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   str
 1   continent  1704 non-null   str
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 80.0 KB

In [ ]:
df['country']   # country 열만 선택하여 새로운 데이터프레임 생성

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: str

In [15]:
country_df = df['country']  
type(country_df)  # country_df의 자료형 확인

pandas.Series

In [ ]:
df[['country', 'continent', 'year']]
# 대괄호가 두개인 이유는, 하나는 데이터프레임의 열을 선택하는 용도이고, 다른 하나는 리스트를 만드는 용도이다.

          country continent  year
0     Afghanistan      Asia  1952
1     Afghanistan      Asia  1957
2     Afghanistan      Asia  1962
3     Afghanistan      Asia  1967
4     Afghanistan      Asia  1972
...           ...       ...   ...
1699     Zimbabwe    Africa  1987
1700     Zimbabwe    Africa  1992
1701     Zimbabwe    Africa  1997
1702     Zimbabwe    Africa  2002
1703     Zimbabwe    Africa  2007

[1704 rows x 3 columns]

In [17]:
subset = df[['country', 'continent', 'year']]
type(subset)

pandas.DataFrame

In [18]:
subset.tail()

       country continent  year
1699  Zimbabwe    Africa  1987
1700  Zimbabwe    Africa  1992
1701  Zimbabwe    Africa  1997
1702  Zimbabwe    Africa  2002
1703  Zimbabwe    Africa  2007

In [ ]:
df.set_index('country')
# 특정 값을 index로 설정하여 데이터프레임을 재구성할 수 있다.
# 따라서 숫자가 아닌 문자열도 index로 설정할 수 있다.
# 이 결과에서 country 열이 index로 설정됨

            continent  year  lifeExp       pop   gdpPercap
country
Afghanistan      Asia  1952   28.801   8425333  779.445314
Afghanistan      Asia  1957   30.332   9240934  820.853030
Afghanistan      Asia  1962   31.997  10267083  853.100710
Afghanistan      Asia  1967   34.020  11537966  836.197138
Afghanistan      Asia  1972   36.088  13079460  739.981106
...               ...   ...      ...       ...         ...
Zimbabwe       Africa  1987   62.351   9216418  706.157306
Zimbabwe       Africa  1992   60.377  10704340  693.420786
Zimbabwe       Africa  1997   46.809  11404948  792.449960
Zimbabwe       Africa  2002   39.989  11926563  672.038623
Zimbabwe       Africa  2007   43.487  12311143  469.709298

[1704 rows x 5 columns]

In [ ]:
# 가장 왼쪽값(인덱스), 딕셔너리와 유사
df.loc[]

# 행의 순서값(무조건 정수), 리스트와 유사
df.iloc[]

# 뒤에서부터 첫번째
df.iloc[-1]

In [24]:
df.loc[0]  # index가 0인 행을 선택하여 새로운 데이터프레임 생성
           # loc와 iloc는 함수가 아니라 속성(attribute)이다. 
           # 따라서 loc와 iloc 뒤에는 괄호가 아닌 대괄호를 사용한다.
           # loc(location) : index를 기준으로 행을 선택
           # iloc(index location) : 행 번호를 기준으로 행을 선택

country      Afghanistan
continent           Asia
year                1952
lifeExp           28.801
pop              8425333
gdpPercap     779.445314
Name: 0, dtype: object

In [ ]:
df.iloc[0:3] # index가 0~2인 행을 선택하여 새로운 데이터프레임 생성

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710

In [22]:
df.loc[0:3] # index가 0~3인 행을 선택하여 새로운 데이터프레임 생성

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138

In [ ]:
df.loc[[0, 1, 10]] 
# index가 0, 1, 10인 행을 선택하여 새로운 데이터프레임 생성
# 원하는 행 여러개를 추출할 수 있다.(대괄호 2개 사용)

        country continent  year  lifeExp       pop   gdpPercap
0   Afghanistan      Asia  1952   28.801   8425333  779.445314
1   Afghanistan      Asia  1957   30.332   9240934  820.853030
10  Afghanistan      Asia  2002   42.129  25268405  726.734055

In [26]:
df.iloc[[0]]
# 데이터프레임으로 반환되므로, 행이 하나라도 데이터프레임으로 반환됨

       country continent  year  lifeExp      pop   gdpPercap
0  Afghanistan      Asia  1952   28.801  8425333  779.445314

In [ ]:
df.loc[0, 'continent']
# [0, 'continent'] : index가 0인 행의 continent 열을 선택하여 새로운 데이터프레임 생성
# 행을 먼저 선택하고, 열을 선택하는 순서로 진행됨
# 행과 열을 동시에 선택하려면 df.loc[행, 열] 형식으로 선택해야 함

'Asia'

In [ ]:
df.info()
# 인포를 통해 컬럼의 인덱스 번호를 확인할 수 있음
# continent 컬럼의 인덱스 번호는 1번임

<class 'pandas.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   str
 1   continent  1704 non-null   str
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 80.0 KB

In [ ]:
df.columns
# 컬럼스를 통해 컬럼의 인덱스 번호를 확인할 수 있음
# 숫자는 안나오지만 리스트 형식이므로
# country 컬럼의 번호는 0번임을 확인할 수 있음

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='str')

In [ ]:
df.iloc[0:5, [1, 5]]
# index가 0~4인 행과, continent(1번), 
# lifeExp(5번) 열을 선택하여 새로운 데이터프레임 생성

  continent   gdpPercap
0      Asia  779.445314
1      Asia  820.853030
2      Asia  853.100710
3      Asia  836.197138
4      Asia  739.981106

In [ ]:
pd.Series()

Series([], dtype: object)

In [33]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [ ]:
pd.Series(['Wes McKinney','Creator of Pandas'])

0         Wes McKinney
1    Creator of Pandas
dtype: str

In [ ]:
pd.Series(['Wes McKinney','Creator of Pandas'], 
          index=['Person','Who'])
# index 인자에 문자열을 리스트로 담아서 전달 가능

Person         Wes McKinney
Who       Creator of Pandas
dtype: str

In [37]:
scientists = pd.DataFrame({
'Name':['Rosaline Franklin','William Gosset'],
'Occupation':['Chemist','Statistician'],
'Born':['1920-07-25','1876-06-13'],
'Died':['1958-04-16','1937-10-16'],
'Age':[37,61]})
scientists

                Name    Occupation        Born        Died  Age
0  Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
1     William Gosset  Statistician  1876-06-13  1937-10-16   61

In [39]:
pd.DataFrame([[1, 2, 3],[4, 5, 6]])

   0  1  2
0  1  2  3
1  4  5  6

In [40]:
pd.DataFrame([[1, 2, 3],[4, 5, 6]], index = [100, 200],
             columns = ['1st', '2nd', '3rd']
             )

     1st  2nd  3rd
100    1    2    3
200    4    5    6

In [ ]:
pd.DataFrame(columns = ['이름', '나이', '폰'])
# 일단 컬럼부터 만들고 값 넣는게 편할 수 있음

Empty DataFrame
Columns: [이름, 나이, 폰]
Index: []

In [51]:
person = pd.DataFrame(columns = ['이름', '나이', '폰'])

person.loc[0] = ['홍길동', 20, '010-1234-5678']
person.loc[3] = ['방현수', 10, '010-3333-4444']

In [52]:
person

    이름  나이              폰
0  홍길동  20  010-1234-5678
3  방현수  10  010-3333-4444

In [53]:
person.loc[(len(person))] = ['김철수', 30, '010-1111-2222']

In [54]:
person

    이름  나이              폰
0  홍길동  20  010-1234-5678
3  방현수  10  010-3333-4444
2  김철수  30  010-1111-2222

In [ ]:
df.values
# 2차원 배열로 변환

array([['Afghanistan', 'Asia', 1952, 28.801, 8425333, 779.4453145],
       ['Afghanistan', 'Asia', 1957, 30.332, 9240934, 820.8530296],
       ['Afghanistan', 'Asia', 1962, 31.997, 10267083, 853.10071],
       ...,
       ['Zimbabwe', 'Africa', 1997, 46.809, 11404948, 792.4499603],
       ['Zimbabwe', 'Africa', 2002, 39.989, 11926563, 672.0386227],
       ['Zimbabwe', 'Africa', 2007, 43.487, 12311143, 469.7092981]],
      shape=(1704, 6), dtype=object)

In [56]:
scientists = pd.read_csv('data/scientists.csv')
ages = scientists['Age']
scientists

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [57]:
ages

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [ ]:
scientists.isin([37, 41, 45])
# []리스트안에 여러개의 값을 넣으면, 
# 그 값들 중 하나라도 있으면 True로 반환됨
# 37, 41, 45라는 값이 하나라도 있으면 True로 반환됨

    Name   Born   Died    Age  Occupation
0  False  False  False   True       False
1  False  False  False  False       False
2  False  False  False  False       False
3  False  False  False  False       False
4  False  False  False  False       False
5  False  False  False   True       False
6  False  False  False   True       False
7  False  False  False  False       False

In [ ]:
scientists.isnull()

    Name   Born   Died    Age  Occupation
0  False  False  False  False       False
1  False  False  False  False       False
2  False  False  False  False       False
3  False  False  False  False       False
4  False  False  False  False       False
5  False  False  False  False       False
6  False  False  False  False       False
7  False  False  False  False       False

In [ ]:
scientists.isnull().sum()   
# True를 숫자 1로 취급
# False는 숫자 0으로 취급

Name          0
Born          0
Died          0
Age           0
Occupation    0
dtype: int64

In [ ]:
scientists.isin([37, 41, 45]).sum()
# isin같은건 단일로 잘 쓰진 않음 .sum()같은걸 붙여서 주로 사용함

Name          0
Born          0
Died          0
Age           3
Occupation    0
dtype: int64

In [63]:
ages.isin([37])
ages.isnull()
ages.count()

np.int64(8)

In [64]:
df['continent'].value_counts()

continent
Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: count, dtype: int64

In [ ]:
df['continent'].unique()    # continent 컬럼의 고유값 확인

<StringArray>
['Asia', 'Europe', 'Africa', 'Americas', 'Oceania']
Length: 5, dtype: str

In [ ]:
print(ages.mean())
print(ages.min())
print(ages.max())
print(ages.quantile (q = 0.25))
# quantile() : 분위수 계산
# q =0.25 : 1사분위수, 
# q=0.5 : 2사분위수(중앙값), 
# q=0.75 : 3사분위수

print(ages.median())

59.125
37
90
44.0
58.5

In [68]:
print(ages.describe())

count     8.000000
mean     59.125000
std      18.325918
min      37.000000
25%      44.000000
50%      58.500000
75%      68.750000
max      90.000000
Name: Age, dtype: float64

In [67]:
scientists.iloc[0]

Name          Rosaline Franklin
Born                 1920-07-25
Died                 1958-04-16
Age                          37
Occupation              Chemist
Name: 0, dtype: object

In [69]:
scientists.describe()

             Age
count   8.000000
mean   59.125000
std    18.325918
min    37.000000
25%    44.000000
50%    58.500000
75%    68.750000
max    90.000000

In [70]:
df.describe()

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [76]:
df.sample()     # 데이터프레임에서 임의의 행을 선택하여 반환

     country continent  year  lifeExp       pop    gdpPercap
677  Hungary    Europe  1977    69.95  10637171  11674.83737

In [75]:
df.sample(5)  # 데이터프레임에서 5개의 임의의 행을 선택하여 반환

               country continent  year  lifeExp         pop     gdpPercap
1331           Senegal    Africa  2007   63.062    12267493   1712.472136
1039        Mozambique    Africa  1987   42.861    12891952    389.876185
1426             Spain    Europe  2002   79.780    40152517  24835.471660
707              India      Asia  2007   64.698  1110396331   2452.210407
835   Korea, Dem. Rep.      Asia  1987   70.647    19067554   4106.492315

In [77]:
df.sample(frac = 0.1)  
# 데이터프레임에서 10%의 임의의 행을 선택하여 반환

                 country continent  year  lifeExp       pop    gdpPercap
340          Congo, Rep.    Africa  1972   54.907   1340458  3213.152683
1273             Romania    Europe  1957   64.100  17829327  3943.370225
439   Dominican Republic  Americas  1987   66.046   6655297  2899.842175
1195            Paraguay  Americas  1987   67.378   3886512  3998.875695
866              Lebanon      Asia  1962   62.094   1886848  5714.560611
...                  ...       ...   ...      ...       ...          ...
1634           Venezuela  Americas  1962   60.770   8143375  8422.974165
1027             Morocco    Africa  1987   62.677  22987397  2755.046991
37                Angola    Africa  1957   31.999   4561361  3827.940465
1683              Zambia    Africa  1967   47.768   3900000  1777.077318
215              Burundi    Africa  2007   49.580   8390505   430.070692

[170 rows x 6 columns]

In [78]:
random = df.sample(frac = 0.1)
random.iloc[0]

country      Korea, Rep.
continent           Asia
year                1962
lifeExp           55.292
pop             26420307
gdpPercap    1536.344387
Name: 842, dtype: object

In [79]:
random = df.sample(frac = 1)    
# 모든 데이터를 섞을때 sample과 frac = 1을 사용
random.iloc[0]

country         Uruguay
continent      Americas
year               1967
lifeExp          68.468
pop             2748579
gdpPercap    5444.61962
Name: 1623, dtype: object

In [80]:
random

          country continent  year  lifeExp        pop     gdpPercap
1623      Uruguay  Americas  1967   68.468    2748579   5444.619620
1492        Syria      Asia  1972   57.296    6701172   2571.423014
1485  Switzerland    Europe  1997   79.370    7193761  32135.323010
1627      Uruguay  Americas  1987   71.918    3045153   7452.398969
1115    Nicaragua  Americas  2007   72.899    5675356   2749.320965
...           ...       ...   ...      ...        ...           ...
1383     Slovenia    Europe  1967   69.180    1646912   9405.489397
1139      Nigeria    Africa  2007   46.859  135031164   2013.977305
538        France    Europe  2002   79.590   59925035  28926.032340
996      Mongolia      Asia  1952   42.244     800663    786.566857
1106    Nicaragua  Americas  1962   48.632    1590597   3634.364406

[1704 rows x 6 columns]

In [81]:
random.sort_index()  # index를 기준으로 정렬

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [82]:
random.sort_index(ascending=False)  # index를 기준으로 내림차순 정렬

          country continent  year  lifeExp       pop   gdpPercap
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
...           ...       ...   ...      ...       ...         ...
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
0     Afghanistan      Asia  1952   28.801   8425333  779.445314

[1704 rows x 6 columns]

In [83]:
scientists.sort_values('Age', ascending = True)  
# Age 컬럼을 기준으로 오름차순 정렬

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
5             John Snow  1813-03-15  1858-06-16   45           Physician
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse

In [ ]:
ages.to_frame()     # 시리즈를 데이터프레임으로 변환

   Age
0   37
1   61
2   90
3   66
4   56
5   45
6   41
7   77

In [85]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [87]:
ages

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [ ]:
ages + ages     # 같은 위치에 있는 값끼리 더해짐
                # series와 series의 연산은 같은 위치에 있는 값끼리 연산이 됨

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [ ]:
ages + 10   # ages의 모든 값이 10씩 증가

0     47
1     71
2    100
3     76
4     66
5     55
6     51
7     87
Name: Age, dtype: int64

In [ ]:
ages > 50       # 비교 연산도 가능

0    False
1     True
2     True
3     True
4     True
5    False
6    False
7     True
Name: Age, dtype: bool

In [ ]:
ages + pd.Series([1, 100])
# NaN은 Not a Number의 약자로, 숫자가 아님을 의미
# 같은 위치에 있는 값끼리 연산이 되므로, index가 일치하지 않으면 NaN이 됨

0     38.0
1    161.0
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
dtype: float64

In [ ]:
ages + pd.Series([1, 100], index = [1, 2])
#

0      NaN
1     62.0
2    190.0
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
dtype: float64

In [ ]:
ages + pd.Series([1, 100], index = ['1st', '2nd'])
# 인덱스를 다르게 지정하면 연산이 되지 않음. index가 일치하지 않으면 NaN이 됨

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
1st   NaN
2nd   NaN
dtype: float64

In [ ]:
rev_ages = ages.sort_index(ascending=False)
# 순서를 역순으로 바꿈

In [ ]:
ages * 2

ages +rev_ages

# 두 코드의 결과가 같음
# rev_ages로 순서를 바꿔도 인덱스는 변하지 않으므로 결과가 같음

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [99]:
scientists['Age'] > scientists['Age'].mean()

0    False
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: Age, dtype: bool

In [100]:
scientists[scientists['Age'] > scientists['Age'].mean()]

                   Name        Born        Died  Age     Occupation
1        William Gosset  1876-06-13  1937-10-16   61   Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90          Nurse
3           Marie Curie  1867-11-07  1934-07-04   66        Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77  Mathematician

In [107]:
scientists.dtypes

Name            str
Born            str
Died            str
Age           int64
Occupation      str
dtype: object

In [ ]:
scientists['Born'].astype('datetime64[ns]')
# 굳이 잘 안쓰지만, astype()을 통해 자료형을 바꿀 수 있음

0   1920-07-25
1   1876-06-13
2   1820-05-12
3   1867-11-07
4   1907-05-27
5   1813-03-15
6   1912-06-23
7   1777-04-30
Name: Born, dtype: datetime64[ns]

In [110]:
died_datetime = pd.to_datetime(scientists['Died'], format='%Y-%m-%d')
print(died_datetime)

0   1958-04-16
1   1937-10-16
2   1910-08-13
3   1934-07-04
4   1964-04-14
5   1858-06-16
6   1954-06-07
7   1855-02-23
Name: Died, dtype: datetime64[us]

In [12]:
import pymysql

import pandas as pd
conn = pymysql.connect(host="localhost", user="root", 
password="1234", port=3306, database="mydb")
users = pd.read_sql('select * from users', conn)
orders = pd.read_sql('select * from orders', conn)
conn.close()

ModuleNotFoundError: No module named 'pymysql'

In [10]:
!pip install pymysql

Requirement already satisfied: pymysql in C:\Program Files\Python314\Lib\site-packages (1.2.0)